In [2]:
from snowflake.snowpark.session import Session
from snowflake.snowpark.types import *
from snowflake.snowpark.functions import col, lit
import getpass
import pandas as pd
import json
from get_secret import get_secret

In [3]:
connection_parameters = json.loads(get_secret())
connection_parameters.update({'warehouse':'COMPUTE_WH', 'database':'ANALYTICS_PROD','schema': 'IOATAWARE',"loglevel":'DEBUG'})
session = Session.builder.configs(connection_parameters).create()

In [4]:
print(f"Current Database and schema: {session.get_fully_qualified_current_schema()}")
print(f"Current Warehouse: {session.get_current_warehouse()}")

Current Database and schema: "ANALYTICS_PROD"."IOATAWARE"
Current Warehouse: "COMPUTE_WH"

In [5]:
snowpark_df = session.table('ANALYTICS_PROD.IOATAWARE.VW_AIF_REPORT_DETAIL')
snowflake_pd_df = snowpark_df.filter(col("Flight Date") == '2023/07/01').to_pandas()

In [6]:
report_df = pd.read_csv('Report_ADD.csv')

In [7]:
snowflake_pd_df.head()

,Flight Date,Departure,Arrival,Reservation Number,Leg Number,PNR,Check In Boarded,Status,First Name,Last Name,Charge Type,Net Charge,Leg Start,Leg End,Charge Date
0,2023/07/01,YYC,YLW,7605501,1,XAJXBZ,B,C,JvdoZhQ/29fWY0HFwWbCReKb5Wqkj6/BKiH4zp92JHo=,0J+RT6YiVBQabr7gClG5ommtqaNBmA8Ghsav5IGegiw=,Airport Improvement Fee,35.0,YYC,YLW,05/21/2023
1,2023/07/01,YYC,YXX,7399891,1,HQZ5C4,B,C,4VPlajgoKh9iV2nqxSav1IFlU80lm77WFD11SYNI+I8=,5eNBlkWn+9XckV3aj51ncc6JNL6T0SlzbSr8yVylXUk=,Airport Improvement Fee,35.0,YYC,YXX,05/03/2023
2,2023/07/01,YHZ,YUL,7118082,1,UPQMGN,B,C,hEA2P39zaPZI7AEby3xujmCanCSX/kaJvDlyZQ2d8JA=,oWEyEvsjwHwHQn4tIrxIYZKXnG98KKdZcRUKaDWceeI=,Airport Improvement Fee,35.0,YHZ,YUL,04/08/2023
3,2023/07/01,YXX,YEG,8028691,1,US9288,B,C,lYYf0O0hju6GLvniL2IjCz6NRo+i7rGlJFpuXWKGrzo=,55/encGrV3wYoTeUGU7aGwuZs6P+9IZJhCsJVg6U5vg=,Airport Improvement Fee,0.0,YXX,YEG,06/27/2023
4,2023/07/01,YEG,YLW,6315258,1,VBGXUF,B,C,gsBijb5Zb/zamC6JxAgGPMvS4LgmscDB3cLVfSRbpvU=,rNbUDymBi3d6P1hQJ0sE9EXN7Icw9S/7uDg0CG3utK4=,Airport Improvement Fee,35.0,YEG,YLW,02/25/2023

In [8]:
report_df

,ExecutionTime2,ExecutionTime3,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,"Flight Start Date: Jul 1, 2023","Flight End Date: Jul 1, 2023",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,FlightDate1,str_Flight_Nmbr,Departure1,Arrival1,lng_Reservation_Nmbr,lng_Res_Legs_Id_Nmbr,PNR,str_Res_CheckIn_Boarded,str_Res_Status,str_First_Name,str_Last_Name,str_GL_Charge_Type_Desc,NetCharge,LegDeparture,LegArrival,ChargeDate
3,7/1/2023,557,YOW,YYC,4465833,9050043,MSDEXN,B,C,TAMARA,JUMAAH,Airport Improvement Fee,$35.00,YOW,YYC,9/11/2022
4,7/1/2023,557,YOW,YYC,4465833,9050044,MSDEXN,B,C,ESTEPHAN,HINDYA,Airport Improvement Fee,$35.00,YOW,YYC,9/11/2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13195,7/1/2023,550,YLW,YYC,8081938,16569236,ERMZ5U,B,C,SHIVASHANKARAN,MUTHUSWAMY,Airport Improvement Fee,$25.00,YLW,YYC,7/1/2023
13196,7/1/2023,550,YLW,YYC,8081938,16569237,ERMZ5U,B,C,JYOTI,SHIVASHANKARAN,Airport Improvement Fee,$25.00,YLW,YYC,7/1/2023
13197,7/1/2023,600,YVR,YYZ,8082791,16570621,28JB4R,B,C,CURTIS,FIRTH,Airport Improvement Fee,$25.00,YVR,YYZ,7/1/2023
13198,7/1/2023,600,YVR,YYZ,8082791,16570622,28JB4R,B,C,TAHNEE,HOLTOM,Airport Improvement Fee,$25.00,YVR,YYZ,7/1/2023
13199,7/1/2023,760,YLW,YEG,8083175,16571062,CJ78TZ,B,C,TANYA,MAIN,Airport Improvement Fee,$25.00,YLW,YEG,7/1/2023

In [13]:
report_df.iloc[2:]

,ExecutionTime2,ExecutionTime3,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
2,FlightDate1,str_Flight_Nmbr,Departure1,Arrival1,lng_Reservation_Nmbr,lng_Res_Legs_Id_Nmbr,PNR,str_Res_CheckIn_Boarded,str_Res_Status,str_First_Name,str_Last_Name,str_GL_Charge_Type_Desc,NetCharge,LegDeparture,LegArrival,ChargeDate
3,7/1/2023,557,YOW,YYC,4465833,9050043,MSDEXN,B,C,TAMARA,JUMAAH,Airport Improvement Fee,$35.00,YOW,YYC,9/11/2022
4,7/1/2023,557,YOW,YYC,4465833,9050044,MSDEXN,B,C,ESTEPHAN,HINDYA,Airport Improvement Fee,$35.00,YOW,YYC,9/11/2022
5,7/1/2023,557,YOW,YYC,4465833,9050045,MSDEXN,B,C,MARTHA,HINDYA,Airport Improvement Fee,$35.00,YOW,YYC,9/11/2022
6,7/1/2023,557,YOW,YYC,4466013,9050396,374BJ9,B,C,SALAM,HINDYA,Airport Improvement Fee,$35.00,YOW,YYC,9/11/2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13195,7/1/2023,550,YLW,YYC,8081938,16569236,ERMZ5U,B,C,SHIVASHANKARAN,MUTHUSWAMY,Airport Improvement Fee,$25.00,YLW,YYC,7/1/2023
13196,7/1/2023,550,YLW,YYC,8081938,16569237,ERMZ5U,B,C,JYOTI,SHIVASHANKARAN,Airport Improvement Fee,$25.00,YLW,YYC,7/1/2023
13197,7/1/2023,600,YVR,YYZ,8082791,16570621,28JB4R,B,C,CURTIS,FIRTH,Airport Improvement Fee,$25.00,YVR,YYZ,7/1/2023
13198,7/1/2023,600,YVR,YYZ,8082791,16570622,28JB4R,B,C,TAHNEE,HOLTOM,Airport Improvement Fee,$25.00,YVR,YYZ,7/1/2023
13199,7/1/2023,760,YLW,YEG,8083175,16571062,CJ78TZ,B,C,TANYA,MAIN,Airport Improvement Fee,$25.00,YLW,YEG,7/1/2023